#ifndef __KEYBOARDCONTROL_H
#define __KEYBOARDCONTROL_H

#include "stm32f1xx_hal.h"
#include "usbd_hid.h"

/* USB键盘编码定义 */
#define KEYBOARD_a_AND_A								4	//KEYBOARD a AND A 
#define KEYBOARD_b_AND_B								5	//KEYBOARD b AND B 
#define KEYBOARD_c_AND_C								6	//KEYBOARD c AND C 
#define KEYBOARD_d_AND_D								7	//KEYBOARD d AND D 
#define KEYBOARD_e_AND_E								8	//KEYBOARD e AND E 
#define KEYBOARD_f_AND_F								9	//KEYBOARD f AND F 
#define KEYBOARD_g_AND_G								10	//KEYBOARD g AND G 
#define KEYBOARD_h_AND_H								11	//KEYBOARD h AND H 
#define KEYBOARD_i_AND_I								12	//KEYBOARD i AND I 
#define KEYBOARD_j_AND_J								13	//KEYBOARD j AND J 
#define KEYBOARD_k_AND_K								14	//KEYBOARD k AND K 
#define KEYBOARD_l_AND_L								15	//KEYBOARD l AND L 
#define KEYBOARD_m_AND_M								16	//KEYBOARD m AND M 
#define KEYBOARD_n_AND_N								17	//KEYBOARD n AND N 
#define KEYBOARD_o_AND_O								18	//KEYBOARD o AND O 
#define KEYBOARD_p_AND_P								19	//KEYBOARD p AND P 
#define KEYBOARD_q_AND_Q								20	//KEYBOARD q AND Q 
#define KEYBOARD_r_AND_R								21	//KEYBOARD r AND R 
#define KEYBOARD_s_AND_S								22	//KEYBOARD s AND S 
#define KEYBOARD_t_AND_T								23	//KEYBOARD t AND T 
#define KEYBOARD_u_AND_U								24	//KEYBOARD u AND U 
#define KEYBOARD_v_AND_V								25	//KEYBOARD v AND V 
#define KEYBOARD_w_AND_W								26	//KEYBOARD w AND W 
#define KEYBOARD_x_AND_X								27	//KEYBOARD x AND X 
#define KEYBOARD_y_AND_Y								28	//KEYBOARD y AND Y 
#define KEYBOARD_z_AND_Z								29	//KEYBOARD z AND Z
#define KEYBOARD_1_AND_EXCLAMATIONMARK					30	//KEYBOARD 1 AND ! 
#define KEYBOARD_2_AND_AT								31	//KEYBOARD 2 AND @ 
#define KEYBOARD_3_AND_SHARP							32	//KEYBOARD 3 AND # 
#define KEYBOARD_4_AND_DOLLAR							33	//KEYBOARD 4 AND $ 
#define KEYBOARD_5_AND_PERCENT							34	//KEYBOARD 5 AND % 
#define KEYBOARD_6_AND_XOR								35	//KEYBOARD 6 AND ^ 
#define KEYBOARD_7_AND_AND								36	//KEYBOARD 7 AND & 
#define KEYBOARD_8_AND_MUL								37	//KEYBOARD 8 AND * 
#define KEYBOARD_9_AND_LEFTPARENTHESES					38	//KEYBOARD 9 AND ( 
#define KEYBOARD_0_AND_RIGHTPARENTHESES					39	//KEYBOARD 0 AND ) 
#define KEYBOARD_ENTER									40	//KEYBOARD ENTER 
#define KEYBOARD_ESCAPE									41	//KEYBOARD ESCAPE 
#define KEYBOARD_BACKSPACE								42	//KEYBOARD BACKSPACE 
#define KEYBOARD_TAB									43	//KEYBOARD TAB 
#define KEYBOARD_SPACEBAR								44	//KEYBOARD SPACEBAR 
#define KEYBOARD_SUB_AND_UNDERSCORE						45	//KEYBOARD - AND _(UNDERSCORE) 
#define KEYBOARD_EQUAL_AND_ADD							46	//KEYBOARD = AND + 
#define KEYBOARD_LEFTSQUAREBRACKETS_AND_LEFTBRACES		47	//KEYBOARD [ AND { 
#define KEYBOARD_RIGHTSQUAREBRACKETS_AND_RIGHTBRACES	48	//KEYBOARD ] AND } 
#define KEYBOARD_BACKSLASH_AND_VERTICALLINE				49	//KEYBOARD \ AND | 
#define KEYBOARD_SEMICOLON_AND_COLON					51	//KEYBOARD ; AND : 
#define KEYBOARD_SINGLEQUOTATIONMARK					52	//KEYBOARD ‘ AND “ 
#define KEYBOARD_GRAVEACCENT_AND_TILDE					53	//KEYBOARD `(GRAVE ACCENT) AND ~(TILDE) 
#define KEYBOARD_COMMA_AND_LESSTHANSIGN					54	//KEYBOARD, AND < 
#define KEYBOARD_FULLSTOP_AND_GREATERTHANSIGN			55	//KEYBOARD . AND > 
#define KEYBOARD_SLASH_AND_QUESTIONMARK					56	//KEYBOARD / AND ? 
#define KEYBOARD_CAPS_LOCK								57	//KEYBOARD CAPS LOCK 
#define KEYBOARD_F1										58	//KEYBOARD F1 
#define KEYBOARD_F2										59	//KEYBOARD F2 
#define KEYBOARD_F3										60	//KEYBOARD F3 
#define KEYBOARD_F4										61	//KEYBOARD F4 
#define KEYBOARD_F5										62	//KEYBOARD F5 
#define KEYBOARD_F6										63	//KEYBOARD F6 
#define KEYBOARD_F7										64	//KEYBOARD F7 
#define KEYBOARD_F8										65	//KEYBOARD F8 
#define KEYBOARD_F9										66	//KEYBOARD F9 
#define KEYBOARD_F10									67	//KEYBOARD F10 
#define KEYBOARD_F11									68	//KEYBOARD F11 
#define KEYBOARD_F12									69	//KEYBOARD F12 
#define KEYBOARD_PRINTSCREEN							70	//KEYBOARD PRINTSCREEN 
#define KEYBOARD_SCROLL_LOCK							71	//KEYBOARD SCROLL LOCK 
#define KEYBOARD_PAUSE									72	//KEYBOARD PAUSE 
#define KEYBOARD_INSERT									73	//KEYBOARD INSERT 
#define KEYBOARD_HOME									74	//KEYBOARD HOME 
#define KEYBOARD_PAGEUP									75	//KEYBOARD PAGEUP 
#define KEYBOARD_DELETE									76	//KEYBOARD DELETE 
#define KEYBOARD_END									77	//KEYBOARD END 
#define KEYBOARD_PAGEDOWN								78	//KEYBOARD PAGEDOWN 
#define KEYBOARD_RIGHTARROW								79	//KEYBOARD RIGHTARROW 
#define KEYBOARD_LEFTARROW								80	//KEYBOARD LEFTARROW 
#define KEYBOARD_DOWNARROW								81	//KEYBOARD DOWNARROW 
#define KEYBOARD_UPARROW								82	//KEYBOARD UPARROW 
#define KEYPAD_NUM_LOCK_AND_CLEAR						83	//KEYPAD NUM LOCK AND CLEAR 
#define KEYPAD_DIV										84	//KEYPAD / 
#define KEYPAD_MUL										85	//KEYPAD * 
#define KEYPAD_SUB										86	//KEYPAD - 
#define KEYPAD_ADD										87	//KEYPAD + 
#define KEYPAD_ENTER									88	//KEYPAD ENTER 
#define KEYPAD_1_AND_END								89	//KEYPAD 1 AND END 
#define KEYPAD_2_AND_DOWN_ARROW							90	//KEYPAD 2 AND DOWN ARROW 
#define KEYPAD_3_AND_PAGEDN								91	//KEYPAD 3 AND PAGEDN 
#define KEYPAD_4_AND_LEFT_ARROW							92	//KEYPAD 4 AND LEFT ARROW 
#define KEYPAD_5										93	//KEYPAD 5 
#define KEYPAD_6_AND_RIGHT_ARROW						94	//KEYPAD 6 AND RIGHT ARROW 
#define KEYPAD_7_AND_HOME								95	//KEYPAD 7 AND HOME 
#define KEYPAD_8_AND_UP_ARROW							96	//KEYPAD 8 AND UP ARROW 
#define KEYPAD_9_AND_PAGEUP								97	//KEYPAD 9 AND PAGEUP 
#define KEYPAD_0_AND_INSERT								98	//KEYPAD 0 AND INSERT 
#define KEYPAD_DOT_AND_DELETE							99	//KEYPAD . AND DELETE 
#define KEYBOARD_APPLICATION							101 
#define KEYBOARD_LEFTCONTROL							224 
#define KEYBOARD_LEFTSHIFT								225 
#define KEYBOARD_LEFTALT								226
#define KEYBOARD_LEFT_GUI								227 
#define KEYBOARD_RIGHTCONTROL							228 
#define KEYBOARD_RIGHTSHIFT								229 
#define KEYBOARD_RIGHTALT								230 
#define KEYBOARD_RIGHT_GUI								231

/* 数组下标值定义 */
#define KEYMAPPING_MODE_NUM								4
#define SENDARRAYLENGTH									8
#define SENDKEYNUM										6
#define KEYNUM											12

/* 外部可调用函数 */
void KeyboardCTRL(void);

#endif
